CI: Import and adapt scripts from osmt
usi-verification-and-security/golem pull request #1
Opened 2022-04-08 14:21 UTC by aehyvari

2022-04-08 16:20 UTC, MasoudAsadzade commented
Nice, LGTM!

2022-04-09 18:32 UTC, blishko requested changes
@aehyvari, thanks for preparing this. I think it will need a few more adjustments. Do you want to do that or should I take over?

2022-04-09 18:32 UTC, blishko commented on .circleci/config.yml
> +                command: sudo apt-get install libgmp-dev libedit-dev bison flex cmake libubsan0 python3-pip cython
`libedit-dev` should not be needed for Golem

2022-04-09 18:32 UTC, blishko commented on .circleci/config.yml
> +                    yum -y install libedit-devel
Same here

2022-04-09 18:32 UTC, blishko commented on .circleci/config.yml
> +                name: Set up model validation environment
This step should be removed.

2022-04-09 18:32 UTC, blishko commented on .circleci/config.yml
> +                    cat ./ci/build_maximally_static.sh |scl enable devtoolset-8 bash
This script is missing now. Maybe it would make sense to have it as well?

2022-04-09 19:42 UTC, aehyvari commented
If you feel like fixing them, I don't want to slow you down. All sounds
good to me!

On Sat, 9 Apr 2022, 20:32 Martin Blicha, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @aehyvari <https://github.com/aehyvari>, thanks for preparing this. I
> think it will need a few more adjustments. Do you want to do that or should
> I take over?
> ------------------------------
>
> In .circleci/config.yml
> <https://github.com/usi-verification-and-security/golem/pull/1#discussion_r846666890>
> :
>
> > +          - image: cimg/base:stable
> +            auth:
> +                username: mydockerhub-user
> +                password: $DOCKERHUB_PASSWORD
> +            environment:
> +                CMAKE_BUILD_TYPE: Release
> +                FLAGS: -Wall -Wextra -Werror
> +
> +        steps:
> +            - checkout
> +            - run:
> +                name: apt-get update
> +                command: sudo apt-get update
> +            - run:
> +                name: install dependencies
> +                command: sudo apt-get install libgmp-dev libedit-dev bison flex cmake libubsan0 python3-pip cython
>
> libedit-dev should not be needed for Golem
> ------------------------------
>
> In .circleci/config.yml
> <https://github.com/usi-verification-and-security/golem/pull/1#discussion_r846666976>
> :
>
> > +              auth:
> +                username: mydockerhub-user
> +                password: $DOCKERHUB_PASSWORD
> +              environment:
> +                CMAKE_BUILD_TYPE: Release
> +                FLAGS: -Wall -Wextra -Werror
> +
> +        steps:
> +            - run:
> +                name: Install the environment
> +                command: |
> +                    yum -y install centos-release-scl
> +                    yum -y install devtoolset-8
> +                    yum -y install gmp-devel
> +                    yum -y install gmp-static
> +                    yum -y install libedit-devel
>
> Same here
> ------------------------------
>
> In .circleci/config.yml
> <https://github.com/usi-verification-and-security/golem/pull/1#discussion_r846667116>
> :
>
> > +                name: Set up newer version of cmake
> +                command: pip3 install cmake
> +            - run:
> +                name: Set up newer version of flex
> +                command: |
> +                    cd ~
> +                    wget --no-verbose "https://github.com/westes/flex/files/981163/flex-2.6.4.tar.gz"
> +                    tar -xvzf flex-2.6.4.tar.gz
> +                    cd flex-2.6.4
> +                    echo "./configure --prefix=/usr/local; make -j4; make install" | scl enable devtoolset-8 bash
> +                    cd ..
> +                    rm -rf flex-*
> +                    flex --version
> +            - checkout
> +            - run:
> +                name: Set up model validation environment
>
> This step should be removed.
> ------------------------------
>
> In .circleci/config.yml
> <https://github.com/usi-verification-and-security/golem/pull/1#discussion_r846667175>
> :
>
> > +                    rm -rf flex-*
> +                    flex --version
> +            - checkout
> +            - run:
> +                name: Set up model validation environment
> +                command: echo 'bash ./regression_models/bin/setup-env.sh' |scl enable devtoolset-8 bash
> +            - run:
> +                name: Debug build gcc under devtoolset-8
> +                command: |
> +                    cat ./ci/run_commands.sh |scl enable devtoolset-8 bash
> +                environment:
> +                    CMAKE_BUILD_TYPE: Debug
> +            - run:
> +                name: Release build gcc under devtoolset-8
> +                command: |
> +                    cat ./ci/build_maximally_static.sh |scl enable devtoolset-8 bash
>
> This script is missing now. Maybe it would make sense to have it as well?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/usi-verification-and-security/golem/pull/1#pullrequestreview-937167456>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB74VMQTTILBYMXHWEM7HMLVEHEKXANCNFSM5S4WWDBQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-10 08:17 UTC, blishko commented on .circleci/config.yml
> +                    cat ./ci/build_maximally_static.sh |scl enable devtoolset-8 bash
I have added the script, but this feature was added to OpenSMT after the last release, so we can enable it only after the next release of OpenSMT.

2022-04-10 08:18 UTC, blishko approved these changes

2022-04-10 08:18 UTC, merged